[[revision_semanal_actualizar]]
1 = "revisar lista de delegados"
2 = "Lista de delegados"
3 = "Clarificación de bandeja de entrada y organización de tareas"
4 = "Revisión de las listas de acciones y proyectos"
5 = "Agenda y calendario de la semana. ¿Que pasó?"
6 = "Sensaciones de la semana"
7 = "Que tal fueron los progresos en el Foco de Atencion Temporal actual"

[[revision_semanal_preparar]]
1 = "Revisar el documento de revisión semanal creado en la anterior etapa"
2 = "Qué puntos de foco tiene el mes/semana?"
3 = "Cómo resulta la importancia de los objetivos definidos frente a estos focos? (actualizar la importancia en base a ello)"
4 = "Re-especificar objetivos de puntos de foco"
5 = "Revisar compromisos del calendario siguientes semanas"
6 = "Revisar si Algun dia tal vez tiene cosas a activar ahora"
7 = "Planificar el calendario de estudio de la semana según el checklist"
8 = "Que necesidades de estudio debo priorizar, de que áreas, cuanto tiempo darle?"
9 = "Organizar sesiones de estudio usando este checklist ￼CHECKLISTS del sistema "
10 = "Según lo que se de los días a vivir, cuando debería descansar y cómo? registrarlo"

[[Procesamiento]]

1 = "Elegir que cosa quiere procesar"

